export const queryKeys = {
  homeFeed: (userId) => ['homeFeed', userId],
  search: (category, query) => ['search', category, query],
  albumDetails: (albumId) => ['albumDetails', albumId],
  artistDetails: (artistId) => ['artistDetails', artistId],
  songDetails: (songId) => ['songDetails', songId],
  profileDetails: (profileId, userId) => ['profileDetails', profileId, userId],
  userRating: (entityType, entityId, userId) => ['userRating', entityType, entityId, userId],
  favorites: (userId) => ['favorites', userId],
  followingDetails: (userId, ids = []) => ['followingDetails', userId, [...ids].sort().join(',')],
  comments: (entityType, entityId, userId) => ['comments', entityType, entityId, userId],
  charts: (entityType, limit) => ['charts', entityType, limit],
  activity: (limit, scope = 'personalized', userId) => ['activity', scope, limit, userId],
  spotifyCurrentlyPlaying: (userId) => ['spotifyCurrentlyPlaying', userId],
  monthlyWrapped: (month, userId) => ['monthlyWrapped', month || 'current', userId],
  profileCompatibility: (profileId, userId) => ['profileCompatibility', profileId, userId],
  badges: (userId) => ['badges', userId],
  tasteWall: (userId) => ['tasteWall', userId],
  premiumInsights: (userId) => ['premiumInsights', userId],
};
